apiVersion: v1
kind: Service
metadata:
  name: {{ include "dialogos-trainer.fullname" . }}
  labels:
    {{- include "dialogos-trainer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "dialogos-trainer.selectorLabels" . | nindent 4 }}
