apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dialogos-trainer
  namespace: dialogos-trainer
  labels:
    app: dialogos-trainer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: dialogos-trainer.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dialogos-trainer
                port:
                  number: 80
