apiVersion: v1
kind: Secret
metadata:
  name: dialogos-trainer-secret
  namespace: dialogos-trainer
  labels:
    app: dialogos-trainer
type: Opaque
stringData:
  ANTHROPIC_API_KEY: ""
  OPENAI_API_KEY: ""
  GEMINI_API_KEY: ""
